project_id = "nkzakwfdaiexpwogezgq"

[auth.email]
  enable_confirmations = false
  otp_length = 8
  otp_expiry = 3600
  max_frequency = "10s"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.notifications-dispatcher]
    verify_jwt = false
  [functions.send-push]
    verify_jwt = false
  [functions.sync-order-statuses]
    verify_jwt = false
  [functions.place-wallet-order]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
